program: ablation-study-jepa
command:
  - ${env}
  - uv
  - run
  - ablation-study-jepa
  - run
  - ${args}
method: grid # values: grid, random, bayes
metric:
  name: val/mse
  goal: minimize # values: minimize, maximize
parameters:
  config:
    value: configs/exp/contrastive_jepa_ablation.yaml
  jepa.num_jepa_layers:
    values: [1, 2, 3, 4]
  jepa.global_weight:
    values: [0.001, 0.01, 0.05, 0.1, 0.2]
  jepa.projection_dim:
    values: [32, 64, 128, 256]
  logging.wandb.enabled:
    value: true
  logging.wandb.mode:
    value: online
  logging.wandb.project:
    value: ablation-study-jepa
